<a href="https://colab.research.google.com/github/arturomf94/ml-mia/blob/master/tarea2/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  

In [86]:
url = 'https://raw.githubusercontent.com/arturomf94/ml-mia/master/tarea2/data.csv'
df = pd.read_csv(url)
df.head()

Compra      Credito  Estudiante  Ingreso    Edad
0     no    excelente          no    medio     >40
1     si   suficiente          si     alto   31…40
2     si    excelente          no    medio   31…40
3     si    excelente          si    medio    <=30
4     si   suficiente          si    medio     >40

In [87]:
df = df.apply(lambda x: pd.factorize(x)[0])
df.head()

Compra   Credito   Estudiante   Ingreso   Edad
0       0         0            0         0      0
1       1         1            1         1      1
2       1         0            0         0      1
3       1         0            1         0      2
4       1         1            1         0      0

In [0]:
X = df.iloc[:, 1:5].values  
y = df.iloc[:, :1].values
X_train = df.iloc[:(df.shape[0] - 5), 1:5].values
X_test = df.iloc[(df.shape[0] - 5):, 1:5].values
y_train = df.iloc[:(df.shape[0] - 5), :1].values
y_test = df.iloc[(df.shape[0] - 5):, :1].values

In [89]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=1)  
classifier.fit(X_train, y_train.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)  

In [91]:
y_pred

array([0, 0, 1, 1, 0])

In [92]:
y_test.ravel()

array([1, 1, 1, 0, 0])

In [93]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[1 1]
 [2 1]]
              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.50      0.33      0.40         3

   micro avg       0.40      0.40      0.40         5
   macro avg       0.42      0.42      0.40         5
weighted avg       0.43      0.40      0.40         5

